CREATE DATABASE market;
GRANT ALL ON market.* TO 'market'@'localhost' IDENTIFIED BY 'MarketPass';
USE market;
CREATE TABLE category(id INT UNSIGNED NOT NULL AUTO_INCREMENT KEY, title VARCHAR(128) NOT NULL, description VARCHAR(256));
CREATE TABLE product (id INT UNSIGNED NOT NULL AUTO_INCREMENT KEY, sku VARCHAR(128), title VARCHAR(128) NOT NULL, description VARCHAR(256), image LONGBLOB, price FLOAT(10) NOT NULL);
